server.port=8081

spring.datasource.url=jdbc:sqlserver://10.131.58.62:1433;databaseName=EHRAssistData;encrypt=true;trustServerCertificate=true
spring.datasource.username=sanjay
spring.datasource.password=san#123456#12
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=Iine0@jd$S10
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

fhir.base.url=http://localhost:8081/baseR4

cors.allowed-origins=http://localhost:3000,http://localhost:4000,http://localhost:5173

firebase.api-key=AIzaSyAXlm95hHdbyXo4VJbOWhvY3D_arreyVjo

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=100

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
